// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: infos.proto

package infos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InfosClient is the client API for Infos service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InfosClient interface {
	LogInfo(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type infosClient struct {
	cc grpc.ClientConnInterface
}

func NewInfosClient(cc grpc.ClientConnInterface) InfosClient {
	return &infosClient{cc}
}

func (c *infosClient) LogInfo(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/infos.Infos/LogInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InfosServer is the server API for Infos service.
// All implementations must embed UnimplementedInfosServer
// for forward compatibility
type InfosServer interface {
	LogInfo(context.Context, *InfoRequest) (*InfoResponse, error)
	mustEmbedUnimplementedInfosServer()
}

// UnimplementedInfosServer must be embedded to have forward compatible implementations.
type UnimplementedInfosServer struct {
}

func (UnimplementedInfosServer) LogInfo(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogInfo not implemented")
}
func (UnimplementedInfosServer) mustEmbedUnimplementedInfosServer() {}

// UnsafeInfosServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InfosServer will
// result in compilation errors.
type UnsafeInfosServer interface {
	mustEmbedUnimplementedInfosServer()
}

func RegisterInfosServer(s grpc.ServiceRegistrar, srv InfosServer) {
	s.RegisterService(&Infos_ServiceDesc, srv)
}

func _Infos_LogInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfosServer).LogInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infos.Infos/LogInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfosServer).LogInfo(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Infos_ServiceDesc is the grpc.ServiceDesc for Infos service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Infos_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infos.Infos",
	HandlerType: (*InfosServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogInfo",
			Handler:    _Infos_LogInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "infos.proto",
}
